config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'pages#home'

  get '/about-us' => 'pages#about_us'
  get '/products' => 'pages#products'
  get '/solutions' => 'pages#solutions'
  get '/contact-us' => 'pages#contact_us'

  get '/admin' => 'admin/posts#index'

  resources :contacts, :only => :create
  resources :recruitments, :only => [:index, :show]

  get '/feed' => 'recruitments#feed'

  namespace :admin do
    resources :dashboard, :only => :index
    resources :posts
    resources :products
  end



end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  name                   :string           not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admins_on_email                 (email) UNIQUE
#  index_admins_on_reset_password_token  (reset_password_token) UNIQUE
#

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  admin_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_posts_on_admin_id  (admin_id)
#

class Post < ActiveRecord::Base
  belongs_to :user

  scope :latest, -> { order(:created_at => :desc) }
  scope :oldest, -> { order(:created_at => :asc) }
  scope :recently_updated, -> { order(:updated_at => :desc) }

  paginates_per 6
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string
#  label               :string
#  description         :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  product_category_id :integer
#  image               :string
#  link                :string
#
# Indexes
#
#  index_products_on_product_category_id  (product_category_id)
#

class Product < ActiveRecord::Base
  belongs_to :product_category

  scope :latest, -> { order(:created_at => :desc) }
end

app/models/product_category.rb
# == Schema Information
#
# Table name: product_categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProductCategory < ActiveRecord::Base
  has_many :products
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminBaseController

  def index
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminBaseController

  before_filter :fetch_post, :only => [:show, :edit, :update, :destroy]


  def index
    @posts = PostDecorator.decorate_collection(Post.latest.page(params[:page]).per 10)
  end

  def show
    @post =  @post.decorate
  end


  def new
    @form = PostForm.new Post.new
  end


  def create
    @form = PostForm.new Post.new

    if @form.validate(post_params) && @form.save
      flash[:notice] = 'Successfully created post!'
      redirect_to [:admin, :posts]
    else
      render :new
    end


  end


  def edit
    @form = PostForm.new @post
  end


  def update
    @form = PostForm.new @post

    if @form.validate(post_params) && @form.save
      flash[:notice] = 'Successfully updated post!'
      redirect_to [:edit, :admin, @post]
    else
      render :edit
    end
  end


  def destroy
    @post.destroy ?
      flash[:notice] = 'Post has been deleted' :
      flash[:notice] = 'Failed to delete post'

    redirect_to [:admin, :posts]
  end





  private

  def post_params
    params.require(:post).permit :title, :content, :admin_id
  end

  def fetch_post
    @post = Post.find params[:id]
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminBaseController

  before_filter :fetch_product, :only => [:show, :edit, :update, :destroy]


  def index
    @products = Product.latest.page(params[:page]).per 10
  end

  def show
  end


  def new
    @form = ProductForm.new Product.new
  end


  def create
    @form = ProductForm.new Product.new

    if @form.validate(product_params) && @form.save
      flash[:notice] = 'Successfully created product!'
      redirect_to [:admin, :products]
    else
      render :new
    end


  end


  def edit
    @form = ProductForm.new @product
  end


  def update
    @form = ProductForm.new @product

    if @form.validate(product_params) && @form.save
      flash[:notice] = 'Successfully updated product!'
      redirect_to [:admin, @product]
    else
      render :edit
    end
  end


  def destroy
    @product.destroy ?
      flash[:notice] = 'Product has been deleted' :
      flash[:notice] = 'Failed to delete product'

    redirect_to [:admin, :products]
  end





  private

  def product_params
    params.require(:product).permit :name, :label, :description, :product_category_id, :image, :link
  end

  def fetch_product
    @product = Product.find params[:id]
  end

end

app/controllers/admin_base_controller.rb
class AdminBaseController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


  def create
    @contact_form = ContactForm.new params


    if @contact_form.validate(params)
      ContactMailer.new_contact(@contact_form).deliver_now

      flash[:notice] = 'We appreciate that you’ve taken the time to write us. We’ll get back to you very soon. Please come back and see us often.'
      redirect_to :back
    else
      render :error
    end
  end


end

app/controllers/contacts_controller0.rb
class ContactsController < ApplicationController


  def create
    @contact_form = ContactForm.new params


    if @contact_form.validate(params)
      ContactMailer.new_contact(@contact_form).deliver_now

      flash[:notice] = 'We appreciate that you’ve taken the time to write us. We’ll get back to you very soon. Please come back and see us often.'
      redirect_to :back
    else
      render :error
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def products
    @security_products = ProductCategory.find_by_name('Security').try :products
    @network_products = ProductCategory.find_by_name('Network').try :products
    @management_products = ProductCategory.find_by_name('Management & Monitoring').try :products
    @datacenter_products = ProductCategory.find_by_name('Datacenter, Backup & Recovery').try :products
    @storage_products = ProductCategory.find_by_name('Storage & Endpoint').try :products
  end


  def solutions
  end


  def contact_us
  end


  def about_us
  end

end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController

  def index
    @posts = PostDecorator.decorate_collection Post.oldest.page(params[:page])
  end


  def show
    @post = Post.find(params[:id]).decorate
  end


  def feed
    @posts = PostDecorator.decorate_collection Post.recently_updated

    respond_to do |format|
      format.rss { render :layout => false }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nl2br text
    text.gsub(/\n/, '%br')
  end


  def title text
    content_for :title, text
  end


  def meta_tag tag, text
    content_for :"meta_#{tag}", text
  end

  def yield_meta_tag tag, default_text = ''
    content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
  end
  
end

app/views/admin/dashboard/index.haml
%h1 Test

app/views/admin/posts/edit.haml
.col-md-6

  %h1 Edit Recruitment Post

  - if flash[:notice]
    .alert.alert-info{:role => 'alert'}= flash[:notice]

  - if @form.errors.present?
    .alert.alert-info{:role => 'alert'}
      = @form.errors.full_messages.first

  = form_for @form, :url => {:action => 'update'} do |f|
    = f.hidden_field :admin_id, :value => current_admin.id
    .form-group
      = f.label :title
      = f.text_field :title, :class => 'form-control', :required => true

    .form-group
      = f.label :content
      = f.text_area :content, :class => 'ckeditor form-control',
        :required => true

    .form-group
      = f.submit 'Submit', :class => 'form-control'

app/views/admin/posts/index.haml
%h1 Recruitments

= link_to 'Create New Recruitment Post', [:new, :admin, :post]

%br
%br
%br

- if flash[:notice]
  .alert.alert-info{:role => 'alert'}= flash[:notice]
  %br

%table.table.table-hover

  %tr
    %th Title
    %th Posted by
    %th Date Created
    %th Date Updated
    %th


  - @posts.each do |post|
    %tr
      %td= post.title
      %td= post.author
      %td= post.date_posted
      %td= post.date_updated
      %td
        = link_to 'View', [:admin, post]
        |
        = link_to 'Edit', [:edit, :admin, post]
        |
        = link_to 'Delete', [:admin, post], :method => :delete

= paginate @posts

app/views/admin/posts/new.haml
.col-md-6

  %h1 Create New Recruitment Post

  - if @form.errors.present?
    .alert.alert-info{:role => 'alert'}
      = @form.errors.full_messages.first

  = form_for @form, :url => {:action => 'create'} do |f|
    = f.hidden_field :admin_id, :value => current_admin.id
    .form-group
      = f.label :title
      = f.text_field :title, :class => 'form-control', :required => true

    .form-group
      = f.text_area :content, :class => 'ckeditor form-control',
        :required => true

    .form-group
      = f.submit 'Submit', :class => 'form-control'


:javascript
  $('.ckeditor').ckeditor({});

app/views/admin/posts/show.haml
= link_to '< Back', [:admin, :posts]

%br
%br

Title:
%strong= @post.title
%br
Posted by:
%strong= @post.author
%br
Date posted:
%strong= @post.date_posted
%br
Date updated:
%strong= @post.date_updated
%br
%br

Content:
%strong= @post.content
%br

app/views/admin/products/edit.haml
.col-md-6

  = link_to '< Back', [:admin, :products]

  %h1 Edit Product

  - if flash[:notice]
    .alert.alert-info{:role => 'alert'}= flash[:notice]

  - if @form.errors.present?
    .alert.alert-info{:role => 'alert'}
      = @form.errors.full_messages.first

  = form_for @form, :url => {:action => 'update'} do |f|
    .form-group
      = f.collection_select :product_category_id,
        ProductCategory.all, :id , :name, {:prompt => 'Please a category'}, :class => 'form-control', :required => true

    .form-group
      = f.label :name
      = f.text_field :name, :class => 'form-control', :required => true

    .form-group
      = f.label :label
      = f.text_field :label, :class => 'form-control', :required => true

    .form-group
      = f.label :link
      = f.text_field :link, :class => 'form-control', :required => true

    .form-group
      = f.label :description
      = f.text_area :description, :class => 'ckeditor form-control',
        :required => true

    .form-group
      = f.label :image, 'Upload Image'
      = f.filepicker_field :image

    .form-group
      = f.submit 'Submit', :class => 'form-control'

app/views/admin/products/index.haml
%h1 Products

= link_to 'Create New Product', [:new, :admin, :product]

%br
%br
%br

- if flash[:notice]
  .alert.alert-info{:role => 'alert'}= flash[:notice]
  %br


- if @products.present?

  %table.table.table-hover

    %tr
      %th Category
      %th Name
      %th Label
      %th


    - @products.each do |product|
      %tr
        %td= product.product_category.name
        %td= product.name
        %td= product.label
        %td
          = link_to 'View', [:admin, product]
          |
          = link_to 'Edit', [:edit, :admin, product]
          |
          = link_to 'Delete', [:admin, product], :method => :delete

  = paginate @products

app/views/admin/products/new.haml
.col-md-6

  = link_to '< Back', [:admin, :products]

  %h1 Create New Product

  - if @form.errors.present?
    .alert.alert-info{:role => 'alert'}
      = @form.errors.full_messages.first

  = form_for @form, :url => {:action => 'create'} do |f|
    .form-group
      = f.collection_select :product_category_id,
        ProductCategory.all, :id , :name, {:prompt => 'Please a category'}, :class => 'form-control', :required => true
    .form-group
      = f.label :name
      = f.text_field :name, :class => 'form-control', :required => true

    .form-group
      = f.label :label
      = f.text_field :label, :class => 'form-control', :required => true

    .form-group
      = f.label :link
      = f.text_field :link, :class => 'form-control', :required => true

    .form-group
      = f.text_area :description, :class => 'ckeditor form-control',
        :required => true

    .form-group
      = f.label :image, 'Upload Image'
      = f.filepicker_field :image

    .form-group
      = f.submit 'Submit', :class => 'form-control'


:javascript
  $('.ckeditor').ckeditor({});

app/views/admin/products/show.haml
.col-md-6
  = link_to '< Back', [:admin, :products]

  %br
  %br

  Category:
  %strong= @product.product_category.name
  %br
  Name:
  %strong= @product.name
  %br
  Label:
  %strong= @product.label
  %br
  Link:
  %strong= @product.link
  %br
  Descrption:
  %strong= @product.description.html_safe
  %br

  Image:
  - if @product.image
    = filepicker_image_tag @product.image, :w => 300, :fit => 'clip'
  - else
    No image yet.

app/views/layouts/_admin_navbar.haml
%nav.navbar.navbar-default.page-header
  .container.nav-container
    .navbar-header
      %button.navbar-toggle.collapsed{'aria-expanded' => 'false', 'data-target' => '#bs-example-navbar-collapse-1', 'data-toggle' => 'collapse', :type => 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.page-header-logo.navbar-brand{:href => '/admin'}
        = image_tag 'gocomsystems-logo.jpg', :alt => 'GOCOM Systems and Solutions Corporation'


    #bs-example-navbar-collapse-1.collapse.navbar-collapse.pull-right
      .page-nav
        %ul.nav.navbar-nav
          %li.page-nav-item
            = link_to 'Recruitments', [:admin, :posts]
          %li.page-nav-item
            = link_to 'Products', [:admin, :products]
          %li.page-nav-item
            = link_to 'Visit Site', '/'
          %li.page-nav-item
            = link_to 'Logout', destroy_admin_session_path,
              :method => :delete


    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/_footer.haml
.bcms-clearfix.custom-clearfix
.bcms-clearfix.custom-clearfix
%footer.page-footer
  .g-container
    .g-lg-8.g-md-12.type-md-center
      Copyright © 2016. GOCOM Systems and Solutions Corporation. All Rights Reserved
    .g-lg-4.g-md-12.type-md-center
      %a{:href => '/privacy-policy'}
      \
      %a{:href => '/sitemap'}
    .page-footer-socials.g-lg-4.g-md-12.type-lg-right
      %a.fa.fa-facebook{:href => 'https://www.facebook.com/gocomsystems/', :target => '_blank', :title => 'Facebook'}
      -# %a.fa.fa-twitter{:href => 'https://www.twitter.com/gocomsystems', :target => '_blank', :title => 'Twitter'}
      %a.fa.fa-linkedin{:href => 'https://www.linkedin.com/company/gocom-systems-and-solutions-corporation', :target => '_blank', :title => 'LinkedIn'}
      %a.fa.fa-rss{:href => '/feed?format=rss', :rel => 'alternate', :title => 'GOCOM RSS Feed', :type => 'application/rss+xml'}
    .bcms-clearfix.custom-clearfix
    .bcms-clearfix.custom-clearfix
.bcms-clearfix.custom-clearfix

app/views/layouts/_navbar.haml
%nav.navbar.navbar-default.page-header
  .container.nav-container
    .navbar-header
      %button.navbar-toggle.collapsed{'aria-expanded' => 'false', 'data-target' => '#bs-example-navbar-collapse-1', 'data-toggle' => 'collapse', :type => 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.page-header-logo{:href => '/'}
        = image_tag 'gocomsystems-logo.jpg', :alt => 'GOCOM Systems and Solutions Corporation'


    #bs-example-navbar-collapse-1.collapse.navbar-collapse.pull-right
      .page-nav
        %ul.nav.navbar-nav
          %li.page-nav-item
            %a.text-bauhaus{:href => '/about-us'} About Us
          %li.page-nav-item
            %a.text-bauhaus{:href => '/products'} Products
          %li.page-nav-item
            %a.text-bauhaus{:href => '/solutions'} Services
          %li.page-nav-item
            %a.text-bauhaus{:href => '/recruitments'} Recruitment
          %li.page-nav-item
            = link_to 'Contact Us', '/contact-us', 'data-no-turbolink' => true,
              :id => 'js-contact-us-link', :class => 'text-bauhaus'

    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/admin.haml
!!!
%html

%head
  = favicon_link_tag 'favicon.ico'
  %title Admin - GOCOM Systems and Solutions Corporation

  = stylesheet_link_tag 'application', :media => 'all',
    'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = filepicker_js_include_tag
  = csrf_meta_tags

%body.loaded
  #wrap.page-wrapper.theme-blue.js-page-wrapper
    = render :partial => 'layouts/admin_navbar'
    %div{:style => 'padding-top: 100px;'}

    .container
      = yield

app/views/layouts/application.haml
!!!
%html

%head
  = favicon_link_tag 'favicon.ico'
  %title
    = if content_for?(:title) then yield(:title) + ' | ' end
    GOCOM Systems and Solutions Corporation

  %meta{:content => "#{yield_meta_tag(:description, 'GOCOM Systems and Solutions Corporation is an Information and Communications Technology company that focuses on Solutions and Services.')}", :name => 'description'}/
  %meta{:content => "#{yield_meta_tag(:keywords, 'gocom,gocomsystems,information,technology,network,solutions,products,services,it,provider,services,makati,philippines')}", :name => "keywords"}/

  = stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track' => true
  = javascript_include_tag 'application'
  = csrf_meta_tags

%body.loaded
  #wrap.page-wrapper.theme-blue.js-page-wrapper
    = render :partial => 'layouts/navbar'
    %main{:role => 'main'}
      = yield
  = render :partial => 'layouts/footer'

app/views/pages/about_us.haml
- title 'About us'
- meta_tag :description, 'The Company was founded in August 9, 2012 in Makati City. We aim to provide not only Network Security products,
but also IT Infrastructure solutions that will help SMB and Enterprise clients'


.page-billboard.page-billboard--xsmall


.g-container
  %article.overview.overview--bg-True
    .overview-text.g-lg-10.g-sm-12.g-lg-push-1.g-sm-push-none
      %div
        %h1
          %span.text-bauhaus Our Company
        %p{:style => 'font-size: 18px; padding: 10px; text-align: center; line-height: 2.5'}
          GOCOM Systems and Solutions Corporation is an Information and
          Communications Technology company that focuses on Solutions and Services.
          %br
          %br
          The Company was founded in August 9, 2012 in Makati City.
          We aim to provide not only Network Security products,
          but also IT Infrastructure solutions that will help SMB and Enterprise clients.
          Continued growth has given us the opportunity to improve our services and look for more cost-effective solutions to address the ever-growing IT need of different industries.

    .g-lg-10.g-sm-12.g-lg-push-1.g-sm-push-none
      %div
        %h1
          %span.text-bauhaus Our Mission

        %p{:style => 'font-size: 18px; padding-top: 10px; text-align: left; line-height: 2.5; text-align: center;'}
          We are an organization committed to provide technology solutions through superior expertise and innovations.
          %br
          We strive to provide optimum value to our customers by pursuing this mission with integrity and creativity.


    .g-lg-10.g-sm-12.g-lg-push-1.g-sm-push-none
      %div
        %h1
          %span.text-bauhaus Our Vision
        %p{:style => 'font-size: 18px; padding-top: 10px; text-align: left; line-height: 2.5; text-align: center;'}
          We bring our global customers to the 21st century through innovative technology solutions that bring their organizations closer to their goals.
          %br

          %i Corporate Core Values:

          .vision-list-container
            %ul
              %li Service
              %li Malasakit
              %li Excellence
              %li Innovation

app/views/pages/contact_us.haml
- title 'Contact Us'
- meta_tag :description, 'Headquarters GOCOM Systems and Solutions Corporation Robinsons Summit Center, Unit 24 Level 12, 6783 Ayala Avenue, Makati, Philippines 1226'

.bcms-clearfix.custom-clearfix
.bcms-clearfix.custom-clearfix
%main{:role => "main"}
  %div
    .page-billboard.page-billboard--contact-us
      .page-billboard-container
        .page-billboard-text
          %h1 GOCOM Systems and Solutions Corporation
          %p Unit 218 Cityland Pioneer, Pioneer St.
          %p Mandaluyong City, Philippines 1550

          .bcms-clearfix.custom-clearfix
        #js-map-canvas.page-billboard-map

    .g-container
      .col-md-11.col-md-offset-1
        %br
        %h1 Contact Us
        %br

      .col-md-5.col-md-offset-1
        - if flash[:notice].present?
          .alert.alert-success.alert-dismissible{:role => "alert"}
            %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
              %span{"aria-hidden" => "true"} ×
            = flash[:notice]

        = form_tag contacts_path, :class => 'elq-form' do |f|
          .form-group
            = text_field_tag :name, nil, :required => true,
              :placeholder => 'NAME', :class => 'form-control'
          .form-group
            = text_field_tag :email, nil, :required => true,
              :placeholder => 'EMAIL', :class => 'form-control'
          .form-group
            = select_tag :subject,
                options_for_select(ContactForm::CONTACT_OPTIONS),
                :prompt => 'Choose a Topic:',
                :required => true, :class => 'form-control'
          .form-group
            = text_area_tag :message, nil, :rows => 6, :required => true,
              :placeholder => 'MESSAGE', :class => 'form-control'
          = submit_tag 'SEND', :class => 'pull-right', :class => 'btn btn-primary form-control'

          %br
          %br

      .col-md-5.col-md-offset-1
        %strong Headquarters
        %p
          Unit 218 Cityland Pioneer, Pioneer St.
          %br/
          Mandaluyong City, Philippines 1550

        %strong Email
        %p
          Sales and Marketing:
          = link_to 'sales@gocom.ph', 'mailto:sales@gocom.ph'
          %br
          Technical Support and Presales:
          = link_to 'support@gocom.ph', 'mailto:support@gocom.ph'

        %strong Phone
        %p
          %a{:href => 'tel: +63026252486', :title => '+63 (02) 625 2486'} +63 (02) 625 2486

        %strong Fax
        %p
          %a{:href => "tel: +63024791555", :title => "+63 (02)479 1555"} +63 (02) 479 1555


        .bcms-clearfix.custom-clearfix
    .bcms-clearfix.custom-clearfix
    .bcms-clearfix.custom-clearfix
.bcms-clearfix.custom-clearfix
.bcms-clearfix.custom-clearfix

.padding-bottom

app/views/pages/home.haml
%div
  .homepage
    .homepage-billboard
      .homepage-billboard
        .homepage-billboard-slides.js-homepage-billboard-slides
          .homepage-billboard-slide.js-homepage-billboard-slide{:style => "background-image: url('/images/we_provide.jpg')"}
            .g-container
              .homepage-billboard-slide-table
                .homepage-billboard-slide-cell
                  %h1{:style => "font-weight: light; color: #fff;"} We provide best-of-breed products to support your IT needs.

                  %p
                    %a{:style => "display: none; font-family: 'Arial'; font-size: 20px; color: #d0ff94", :href => "/products", :title => "Learn More"} Learn More
          .homepage-billboard-slide.js-homepage-billboard-slide{:style => "background-image: url('/images/we_deliver.jpg')"}
            .g-container
              .homepage-billboard-slide-table
                .homepage-billboard-slide-cell
                  %h1{:style => "font-weight: light; color: #fff;"} We deliver turn-key solutions to free you from the woes of IT Project implementations.

                  %p
                    %a{:style => "display: none; font-size: 20px; color: #d0ff94", :href => "/solutions", :title => "Learn More"} Learn More
          .homepage-billboard-slide.js-homepage-billboard-slide{:style => "background-image: url('/images/we_keep.jpg')"}
            .g-container
              .homepage-billboard-slide-table
                .homepage-billboard-slide-cell
                  %h1{:style => "font-weight: light; color: #fff;"} We keep your IT systems up and running to let you focus more on running your business.

                  %p
                    %a{:style => "display: none; font-size: 20px; color: #d0ff94", :href => "/solutions", :title => "Learn More"} Learn More
        .social-slider-pager.js-homepage-billboard-pager
        %i.social-slider-prev.fa.fa-angle-left.js-homepage-billboard-prev
        %i.social-slider-next.fa.fa-angle-right.js-homepage-billboard-next
      .social-slider-pager.js-homepage-billboard-pager
      %i.social-slider-prev.fa.fa-angle-left.js-homepage-billboard-prev
      %i.social-slider-next.fa.fa-angle-right.js-homepage-billboard-next
    .bcms-clearfix.custom-clearfix

    .container.padding-top.category-container
      .row.padding-bottom-half.category-parent.no-padding
        .col-md-4
          .category-component
            .holder
              .bg-cover
                = image_tag 'tabs/solutions.jpg'
              .text-box
                %a.button.blue{:href => '/about-us'} About Us
                %p GOCOM Systems and Solutions Corporation is an Information and Communications Technology company that focuses on Solutions and Services.
        .col-md-4
          .category-component
            .holder
              .bg-cover
                = image_tag 'tabs/products.jpg'
              .text-box{'data-href' => '#'}
                %a.button.blue{:href => '/products'} Products
                %p In order for us to supply you with a complete Hardware and Software solution we are able to offer you a wide range of hardware and software licencing as well as all the peripherals you may need.

        .col-md-4
          .category-component
            .holder
              .bg-cover
                = image_tag 'tabs/about-us.jpg'
              .text-box
                %a.button.blue{:href => '/solutions'} Services
                %p As a leading digital solution provider supported by the best technology and expertise, we offer global compliance, digital experience and content solutions.

      .bcms-clearfix.custom-clearfix

    .article-columns
      %article.contact-us-message
        .g-container
          .g-lg-12
            %h1 Get In Touch
            %p Whether you are looking for general information or have a specific question, we want to help.
            %a.button-primary{:href => "/contact-us", :title => "Contact Us"} Contact Us

app/views/recruitments/index.haml
- title 'Recruitment'
- meta_tag :description, "Learn about GOCOM's recruiting programs, and browse open jobs."

.page-path{:style => 'padding-top: 85px;'}
  .g-container
    .g-lg-12
      |
      &nbsp;
      - @posts.each do |post|
        %a{:href => "#recruitment-#{post.id}"}= post.title
        &nbsp;
        |



.g-container
  .g-lg-12
    %article.overview--bg-True.text-page.g-lg-12.products-container
      %section
        - @posts.each do |post|
          .overview-text.g-lg-10.g-sm-12.g-lg-push-1.g-sm-push-none.background-none{:id => "recruitment-#{post.id}"}
            %div.text-center
              = link_to "/recruitments/#{post.id}", :class => 'recruitment-link' do
                %h1.product-group
                  %span{:style => "font-size:24px;"}= post.title
              %span{:style => 'margin-top: -50px !important;'}
                Posted #{post.date_posted} by #{post.author}

            .person-anchor &nbsp;

            %p= post.content.html_safe

  .g-lg-12.text-center
    = paginate @posts

  %a{:href => "#0", :class=> "cd-top"}